### PR TITLE
feat : Migrate hardcoded dimensions to value file

### PR DESCRIPTION
**Pull request by Ana2k**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straighforward changes).**

Fixes #[407]

**Description**
Migrated hardcoded dimension values from XML files to value files. 

**Alternative(s) considered**
N/A

**Type**
Choose one: (Code health)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledge the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Comment by Ana2k** [comment]
@jingtang10  I have migrated the hardcoded dimensions to value files. Please review this pr. Thanks!

**Review by jingtang10 — CHANGES_REQUESTED** [review]
thanks for your contribution.

`cqlreferece` and `referece` UI is going to change a lot and I really don't think extracting dimens values is a priority. please revert those changes.

**Comment by jingtang10** [comment]
please remove "feat" in the PR title since this is not a feature.

**Comment by Ana2k** [comment]
> thanks for your contribution.
> 
> `cqlreferece` and `referece` UI is going to change a lot and I really don't think extracting dimens values is a priority. please revert those changes.

Thanks for the heads up. I will surely make the suggested changes.
I had a question, What are the high priority issues for the upcoming weeks?
Does testing of datacapture or further relevant changes in the datacapture module fall under this?

**Comment by jingtang10** [comment]
@Ana2k apologies but I think it's actually best to close this PR and the issue itself. If you are keen to contribute please pick up some other tasks.

**Pull request closed without merging**
