### PR TITLE
Add patient screen.

### LINKED ISSUE #590: Create "Add patient" screen
**Is your feature request related to a problem? Please describe.**
We need to add an 'add patient' screen to the reference application

**Describe the solution you'd like**

**User story:** As a user I can register a new patient using the client application

Requirements:

- [ ] add a dependency from the reference application to the data capture library (`datacapture` mdoule)
- [ ] create a FHIR questionnaire resource which can be stored in the assets folder in the reference app that defines the questions to be asked while registering a patient (ask @fredhersch)
- [ ] use the `QuestionnaireFragment` to render the above questionnaire
- [ ] a new 'add patient' button (e.g. FAB https://material.io/components/buttons-floating-action-button) on the patient list screen
- [ ] modify the navigation graph so that clicking the add patient button would take the user to the new fragment
- [ ] use the `ResourceMapper` API to create a patient from the questionnaire response
- [ ] save the resulting patient into the db using the FHIR engine API
- [ ] show the new patient in the patient list view

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #590 

**Description**
Add a dependency from the reference application to the data capture library (datacapture mdoule)
Create a FHIR questionnaire resource which can be stored in the assets folder in the reference app that defines the questions to be asked while registering a patient 
Use the QuestionnaireFragment to render the above questionnaire
A new 'add patient' button (e.g. FAB https://material.io/components/buttons-floating-action-button) on the patient list screen
Modify the navigation graph so that clicking the add patient button would take the user to the new fragment
Use the ResourceMapper API to create a patient from the questionnaire response
Save the resulting patient into the db using the FHIR engine API
Show the new patient in the patient list view

**Alternative(s) considered**
No

**Type**
Choose one: (Feature)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Comment by santosh-pingle** [comment]
[Duplicate Files Exception #614](https://github.com/google/android-fhir/issues/614)

**Comment by Tarun-Bhardwaj** [comment]
@aditya-07 , assigning it to you for reviewing the code changes.

**Review by jingtang10 — COMMENTED** [review]
@santosh-pingle thanks for this PR! Great work!

Please just address the comment on ID left in the issue. We should be good to go after that!

**Review by aditya-07 — APPROVED** [review]

**Comment by santosh-pingle** [comment]
> @santosh-pingle thanks for this PR! Great work!
> 
> Please just address the comment on ID left in the issue. We should be good to go after that!

Done.

**Pull request merged**
