### PR TITLE
Primitive converter poet

### LINKED ISSUE #559: Feat : Add functionality to convert between primitive datatypes
Describe the solution you'd like

Add functionality to convert between primitive types in the Hapi<>Proto converter using code generation

Describe alternatives you've considered

Cloud also have been done by reflection however code generation would be much faster than reflection.

Additional context
GSoC project

### PR DESCRIPTION
**Pull request by epicadk**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #559 

**Description**
Clear and concise code change description. 

add functionality to convert between primitive types  using java code generation

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

described in issue.

TODO 

1. Add license
2. Create gradle task to generate these files 
3. Exclude from spotless ?
4. figure out how to inline return statement in toProto method.

**Type**
  Feature

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Comment by epicadk** [comment]
Will get it done by the end of this week. @Tarun-Bhardwaj

**Comment by epicadk** [comment]
@Rkareko @jingtang10 could you review this? The resource and complex type generators are also almost done so if this is good to merge I can also open a pr for those.

**Comment by epicadk** [comment]
Using top level functions. I'll add the reasoning in the design doc.

**Comment by Tarun-Bhardwaj** [comment]
@jingtang10 / @aditya-07 , could you please review the changes?

**Comment by epicadk** [comment]
> @jingtang10 / @aditya-07 , could you please review the changes?

Actually when speaking to jing he mentioned that this does not require codeowner approval because the base branch is not master. 
This is a part of my GSoC project. So I think a review from @Rkareko would be enough to merge changes. After the program is over I can open a pr to master that could be reviewed by the codeowners. cc @jingtang10

**Pull request closed without merging**
