### PR TITLE
resolve failing CI

### PR DESCRIPTION
**Pull request by epicadk**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[issue number]

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Comment by FikriMilano** [comment]
@epicadk In my case, I got an OOM the last time I pushed a code. Works fine locally though

**Comment by epicadk** [comment]
> @epicadk In my case, I got an OOM the last time I pushed a code. Works fine locally though

Yeah what's weird is this time it's failing only on the coverage step (where I increased the ram).

**Comment by jingtang10** [comment]
@stevenckngaa not sure if you can shed a light on this.

What i've noticed locally is that if i run the instrumentation tests on my pixel6 everything passes, but if i run it on nokia 4.2 it fails.

so i wonder if this is related to any recent emulator update similar to what happened in https://github.com/ReactiveCircus/android-emulator-runner/issues/160

i am also trying to resolve this in https://github.com/google/android-fhir/pull/1118 but haven't gone very far

**Comment by jingtang10** [comment]
doesn't look like the change worked :(

**Comment by epicadk** [comment]
not a ram issue maybe bumping the dependencies might work?

**Comment by jingtang10** [comment]
Amazing @epicadk

**Review by jingtang10 — APPROVED** [review]

**Comment by epicadk** [comment]
I think @stevenckngaa did something similar in #1125 😅

**Comment by jingtang10** [comment]
maybe it was a fluke when all the tests passed?

**Pull request merged**
