### PR TITLE
Allow modification of Questionnaire submit action button text via configuration

### PR DESCRIPTION
**Pull request by DebbieArita**
…figuration

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes https://github.com/google/android-fhir/issues/2239

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Review by ellykits — CHANGES_REQUESTED** [review]

**Review by MJ1998 — APPROVED** [review]
LGTM

**Comment by DebbieArita** [comment]
@santosh-pingle @MJ1998 could you help me resolve the Kokoro check and maybe point out anything else I need to close on this?

**Comment by MJ1998** [comment]
@DebbieArita 
Kokoro is running right now. Let's wait for the result.

**Comment by DebbieArita** [comment]
@santosh-pingle @MJ1998 could you help me resolve the Kokoro check and maybe point out anything else I need to close on this? 

> @DebbieArita Kokoro is running right now. Let's wait for the result.

Alright, thank you.

**Review by jingtang10 — CHANGES_REQUESTED** [review]
Please try to add this line:

```
    <string name="submit_questionnaire">New Submit String</string>
```

to the resource files in your app, and I think it'll override the string value in the library resources.

and if you really need to do this at run-time (which I'm not too keen on actually), you can do it this way: https://blog.kiprosh.com/how-to-replace-strings-xml-dynamically-in-android/

Please try this and see if this works better for you. My concern here is that if we provide an API / configuration for each string we'll end up with a ton of new API surfaces... and I worry that we'll struggle to manage.

**Comment by ellykits** [comment]
@jingtang10 Changing the text via the `strings.xml` file would be the easiest however, this would change the text through the application which is not desired in our current use case. We'd want to change the texts only for particular questionnaires. 

cc @DebbieArita

**Comment by ellykits** [comment]
> and if you really need to do this at run-time (which I'm not too keen on actually), you can do it this way: https://blog.kiprosh.com/how-to-replace-strings-xml-dynamically-in-android/
> 
> Please try this and see if this works better for you. My concern here is that if we provide an API / configuration for each string we'll end up with a ton of new API surfaces... and I worry that we'll struggle to manage.

I missed reading this part of your comment @jingtang10. We only required the update for the questionnaire submission text. We'll try the suggestion.

**Review by jingtang10 — APPROVED** [review]
i think this change alone is fine. but let's be careful with introducing too many arguments in the future.

**Pull request merged**
