### PR TITLE
[WIP]: Fhir implementaion patients module page

### LINKED ISSUE #598: Implementation of FHIR Profiles
**Is your feature request related to a problem? Please describe.**
* Accessing IPS URL and creating a place to store the data
* Creating a package or module as required or even within the Reference App.
* Rendering the list of patients, and ability to store detailed summary
→ Summary will include all medical history of patient
→ Including organisations, medical professionals treating and taking care at that time.

**Describe the solution you'd like**
*Implementation of International patient page according to 
http://hl7.org/fhir/uv/ips/
*Render the patient list accordingly using 
http://hl7.org/fhir/R4/patient.html and http://hl7.org/fhir/uv/ips/ipsStructure.html

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Would you like to work on the issue?**
Yes.

### PR DESCRIPTION
**Pull request by Ana2k**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #598 

**Description**
Implementation of IPS section in the FHIR module

**Alternative(s) considered**
N/A

**Type**
Choose one: Feature 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [ ] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Comment by Ana2k** [comment]
@maimoonak you can check out this pr for updates regarding the assigned part.

**Comment by jingtang10** [comment]
hi @Ana2k if this is part of the gsoc project can you create a feature branch for your development and make sure you sync with the latest changes from time to time? as it stands i don't think this should be part of the reference app but open to discussion.

can we also have a discussion about what exactly is to be implemented in the new screen? thanks

**Comment by Tarun-Bhardwaj** [comment]
> hi @Ana2k if this is part of the gsoc project can you create a feature branch for your development and make sure you sync with the latest changes from time to time? as it stands i don't think this should be part of the reference app but open to discussion.
> 
> can we also have a discussion about what exactly is to be implemented in the new screen? thanks

@Ana2k , based on Jing's comments above, can this PR please be closed?

**Comment by Ana2k** [comment]
@Tarun-Bhardwaj closing this pr as instructed and creating feature branch.

**Pull request closed without merging**
