### PR TITLE
Update padding for the helper icon.

### LINKED ISSUE #2093: Help icon cropped (a bit on the right side)
**Describe the bug**
Right side of the help icon is cropped a little bit.

Screen Shot 2023-07-22 at 18 42 28

**Component**
SDC library

**To Reproduce**

**Expected behavior**
It should not cropped.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
N/A

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2093

**Description**
Default padding of icon in TextButton was pushing icon to the right end, as result icon appeared as cut on right side.
Default padding is overridden so that it will not pushed to the right side.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Comment by santosh-pingle** [comment]
Screenshot 2023-08-01 at 1 33 28 PM

**Review by jingtang10 — CHANGES_REQUESTED** [review]
it looks like the help icon is 48x48px... but i don't understand why it's more cropped given the height and width are 24dp. does this mean android is automatically scaling the image? and if so, why isn't it scaled perfectly since 48x48 and 24x24 are both perfectly square? what's causing the crop on the right?

can you update the xml file itself to see a 24x24 icon would work better?

by changing the size to 28 we're making the row taller, right?

@shelaghm

**Comment by santosh-pingle** [comment]
> it looks like the help icon is 48x48px... but i don't understand why it's more cropped given the height and width are 24dp. does this mean android is automatically scaling the image? and if so, why isn't it scaled perfectly since 48x48 and 24x24 are both perfectly square? what's causing the crop on the right?
> 
> can you update the xml file itself to see a 24x24 icon would work better?
> 
> by changing the size to 28 we're making the row taller, right?
> 
> @shelaghm

Done.
Added custom style for help button, where padding is overridden around the icon.

**Comment by santosh-pingle** [comment]
Screenshot 2023-08-30 at 4 04 36 PM

**Pull request merged**
