### PR TITLE
Do not create LocalChanges when inserting synced resources

### LINKED ISSUE #300: Do not create local change when syncing resources
Insert synced resources using `insertRemote()/insertAllRemote()`

### PR DESCRIPTION
**Pull request by deepankarb**
Fixes #300

### CODE REVIEW

**Review by jingtang10 — COMMENTED** [review]
thanks @deepankarb :)

same in this PR: what tests should we have had that should have failed for this code change?

**Comment by deepankarb** [comment]
> thanks @deepankarb :)
> 
> same in this PR: what tests should we have had that should have failed for this code change?

@jingtang10 Individually both resource sync and local change management work fine.  Integration tests for resource sync are missing :)

**Comment by jingtang10** [comment]
https://github.com/google/android-fhir/pull/294 has been merged. So please rebase your branch onto `master` (or merge `master` into your feature branch if rebase is too difficult) and follow [this section](https://github.com/google/android-fhir/wiki/Developer's-Guide#kotlin-coding-conventions) in the developer's guide to set up your environment to use the new coding conventions. Thanks!

**Comment by jingtang10** [comment]
> > thanks @deepankarb :)
> > same in this PR: what tests should we have had that should have failed for this code change?
> 
> @jingtang10 Individually both resource sync and local change management work fine. Integration tests for resource sync are missing :)

can you create an issue and link here?

**Review by jingtang10 — CHANGES_REQUESTED** [review]
please request review again after creating issue.

**Review by jingtang10 — APPROVED** [review]

**Pull request merged**
