### PR TITLE
Update HAPI structures lib version to 6.0.1

### PR DESCRIPTION
**Pull request by jingtang10**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

**Description**
Update HAPI structures lib version to 6.0.1

**Alternative(s) considered**
NA

**Type**
Builds

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Comment by jingtang10** [comment]
@vitorpamplona: I tried to use HAPI6 in this separate PR. Would you please take a look at this PR? Thanks!

**Review by omarismail94 — APPROVED** [review]

**Comment by jingtang10** [comment]
I tested this on Android API level 24.

Discussed this with @vitorpamplona. While his PR #1603 does reveal issues with usage of HAPI6, it is caused due to the CQL dependencies exercising code paths not previously used in the engine and sdc libs.

For that reason I will go ahead with this PR.

**Review by vitorpamplona — APPROVED** [review]
It should work just fine.

**Comment by vorburger** [comment]
https://github.com/google/android-fhir/wiki/External-Dependencies now documents this.

**Pull request merged**
