### PR TITLE
Update the license header to 2022

### PR DESCRIPTION
**Pull request by jingtang10**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
NA

**Type**
Documentation

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Comment by omarismail94** [comment]
Is it better to have a date range: 2021-2022, or just 2022? wdyt?

**Comment by jingtang10** [comment]
> Is it better to have a date range: 2021-2022, or just 2022? wdyt?

Actually I think i'll try this: https://github.com/diffplug/spotless/tree/main/plugin-gradle#ratchet

And discussion here: https://github.com/diffplug/spotless/issues/183

**Comment by jingtang10** [comment]
> > Is it better to have a date range: 2021-2022, or just 2022? wdyt?
> 
> Actually I think i'll try this: https://github.com/diffplug/spotless/tree/main/plugin-gradle#ratchet
> 
> And discussion here: [diffplug/spotless#183](https://github.com/diffplug/spotless/issues/183)

this is done. @omarismail94 ptal! thanks!

**Comment by jingtang10** [comment]
as you can see this change took effect on itself. the header file of the spotlessconfig.kt file has been updated.

**Comment by jingtang10** [comment]
Unfortunately github actions seem to be failing

```
FAILURE: Build failed with an exception.
6 actionable tasks: 6 executed
* Where:
Build file '/Users/runner/work/android-fhir/android-fhir/build.gradle.kts' line: 23
* What went wrong:
No such reference 'origin/master'
```

looking 👀

**Pull request merged**
