### PR TITLE
cleaned up old state for dropdown

### LINKED ISSUE #1775: Selected option in dropdown being copied across pages in a paginated questionnaire
**Describe the bug**
When an option has been selected on a dropdown on one page, the selected option is displayed as the default value of a separate dropdown on another page.

**Component**
SDC library

**To Reproduce**
N/A

**Expected behavior**
I expect any subsequent dropdowns to **not** have their default value set as the chosen value of a preceding dropdown

**Screenshots**
As can be seen from the [video](https://user-images.githubusercontent.com/90775548/209078716-f96b080f-d64e-4d1c-80e0-30923fb2609b.mp4), 'Chauluka' is selected as the tracing catchment in the location information page. When proceeding to the phone information page, 'Chauluka' is shown as the default value for the type of phone number even though it is not one of the options for that dropdown.

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
Here is the [questionnaire](https://github.com/google/android-fhir/files/10284591/sample_registration_questionnaire.txt) used

### PR DESCRIPTION
**Pull request by PallaviGanorkar**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1775

**Description**
cleaned up old state for dropdown by setting null value

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Comment by PallaviGanorkar** [comment]
@aditya-07  As discussed, 

- This fix works fine for paginated layout as well as single screen with scroll bar
- Also it works fine for extracting response from questionnaire

**Comment by PallaviGanorkar** [comment]
@aditya-07 As discussed, here are the videos for both default and paginated layout

https://user-images.githubusercontent.com/13957417/210226735-62631a01-0933-4c80-9385-993f7c44ea12.mp4

https://user-images.githubusercontent.com/13957417/210226767-d794a187-780b-4e85-8f3e-5fa18840c4f2.mp4

**Review by jingtang10 — CHANGES_REQUESTED** [review]
thanks for catching this!

is there a test case to add?

**Comment by PallaviGanorkar** [comment]
> 

Done

**Comment by PallaviGanorkar** [comment]
> thanks for catching this!
> 
> is there a test case to add?

Done

**Review by jingtang10 — APPROVED** [review]

**Pull request merged**
