### PR TITLE
Add generated docs for sdc-0.1.0-beta03, engine-0.1.0-beta01, workflow-0.1.0-alpha01

### LINKED ISSUE #1457: Integrate Dokka into all SDK components and build API reference docs
**Describe the Issue**
Kotlin's documentation generation tool is called [Dokka](https://github.com/Kotlin/dokka). API reference docs should be available for developers, and rebuilding them should be a part of every release. Looking at the diff in generated reference docs between versions is a strong tool for understanding changes between versions. Code-level documentation is also tightly integrated with Android Studio, e.g. shows up when you hover over components in the code. Generating docs would also help identify where documentation is lacking or not keeping up with style guide expectations.

### PR DESCRIPTION
**Pull request by williamito**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1457 

**Description**
Generated reference docs for each library's latest released version by doing e.g. `git checkout tags/sdc-0.1.0-beta03 -b sdc-0.1.0-beta03` and running a gradle task similar to PR #1466 .

**Alternative(s) considered**
Placing docs into a version-named directory
* Pros: Previous docs versions easily available
* Cons: More difficult to see diff between versions at release

**Type**
Documentation

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Comment by jingtang10** [comment]
Can you please document the gradle task to run to generate the docs?

**Comment by williamito** [comment]
Catching back up after vacation.

@jingtang10 
1. How would you like the gradle tasks documented?
2. The hyphens are because Java/Kotlin are case-sensitive, and the doc generator converts uppercase characters to `-[lower]`, e.g. `A` becomes `-a`. If the thing is in all caps, it turns into a gross filename. I believe the rendered version is fine though. See https://github.com/Kotlin/dokka/issues/2229

**Comment by jingtang10** [comment]
> Catching back up after vacation.
> 
> @jingtang10
> 
> 1. How would you like the gradle tasks documented?

When do they need to be run? Each time we make a release? In that case should be documented in our release process.

> 2. The hyphens are because Java/Kotlin are case-sensitive, and the doc generator converts uppercase characters to `-[lower]`, e.g. `A` becomes `-a`. If the thing is in all caps, it turns into a gross filename. I believe the rendered version is fine though. See [Make uppercase-to-lowercase file name conversion configurable Kotlin/dokka#2229](https://github.com/Kotlin/dokka/issues/2229)

ah ok if this is just a dokka thing and we can't control it's fine.

**Comment by jingtang10** [comment]
how can we preview this docs?

**Comment by williamito** [comment]
> When do they need to be run? Each time we make a release? In that case should be documented in our release process.

Correct - I will update the release documentation with instructions after #1466 is merged. I'll also need to regenerate the data capture docs to reflect the values in Releases.kt (`datacapture` vs `data-capture`)

**Review by jingtang10 — CHANGES_REQUESTED** [review]
Looks like `/docs/engine/html/engine` is a duplicate of `/docs/engine/engine`?

`sdc` and `workflow` don't have the `html/` subdiretory.

**Comment by williamito** [comment]
> Looks like `/docs/engine/html/engine` is a duplicate of `/docs/engine/engine`?
> 
> `sdc` and `workflow` don't have the `html/` subdiretory.

Fixed, I must have messed up copying docs around to generate at 3 different tags.

**Review by jingtang10 — APPROVED** [review]
thanks for this

**Pull request merged**
