### PR TITLE
App exits on patient details screen. 

### LINKED ISSUE #701: Patient details card : java.lang.NullPointerException: observationCode must not be null
**Describe the bug**
Issue was seen on patient details card.

java.lang.NullPointerException: observationCode must not be null
        at com.google.android.fhir.reference.PatientDetailsViewModel.createConditionItem(PatientDetailsViewModel.kt:119)
        at com.google.android.fhir.reference.PatientDetailsViewModel.getPatientConditions(PatientDetailsViewModel.kt:67)
        at com.google.android.fhir.reference.PatientDetailsViewModel$getPatientConditions$1.invokeSuspend(Unknown Source:11)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Component**
reference app

**To Reproduce**
Patient search page -> click on patient -> click on complete survey -> answers the questions -> Submit
App. crash on patient details screen.

 Patient search page -> click on patient (who participated screen encounter survey)-
App. crash on patient details screen.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #701 

**Description**
Resource without answer was saved in db.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix)

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Comment by jingtang10** [comment]
thanks for the fix @santosh-pingle! my concern here is why does the app crash? if the observation is missing code the app should be able to handle it. filtering this out isn't fixing the real issue.

**Comment by Tarun-Bhardwaj** [comment]
> thanks for the fix @santosh-pingle! my concern here is why does the app crash? if the observation is missing code the app should be able to handle it. filtering this out isn't fixing the real issue.

@santosh-pingle , any update on this PR? It seems a response is awaited here.

**Comment by santosh-pingle** [comment]
Please ignore this PR, I will close it.
It is not required anymore.

**Comment by Tarun-Bhardwaj** [comment]
> Please ignore this PR, I will close it.
> It is not required anymore.

@santosh-pingle , do you still want to keep this PR open?

**Comment by santosh-pingle** [comment]
> > Please ignore this PR, I will close it.
> > It is not required anymore.
> 
> @santosh-pingle , do you still want to keep this PR open?
 Closing it right now, issue was already closed.

**Pull request closed without merging**
