### PR TITLE
Added Support for optionExclusive Extension in Popup

### LINKED ISSUE #2436: Questionnaire AnswerOption optionExclusive Extension does not work in Popup
**Describe the bug**
`optionExclusive` feature has been implemented here #1281. However, when options appear in a popup (if there are more than ten items), this doesn't work.

**Component**
SDC library

**To Reproduce**
This questionnaire doesn't work as expected when choosing an option with `optionExclusive` extension. e.g. **No Problem**.

```
{
  "resourceType": "Questionnaire",
  "item": [
    {
      "linkId": "9b585e14-2d7c-4391-8c89-01f5474c3f9c",
      "type": "choice",
      "text": "Reason for Referral",
      "required": true,
      "repeats": true,
      "answerOption": [
        {
          "valueCoding": {
            "id": "0b2e1881-b37f-4f9f-8abe-fbc172b15307",
            "code": "pregnancy_problems",
            "system": "urn:uuid:fca5e3c1-1f62-4d7c-97a4-f03303c1a659",
            "display": "Pregnancy Problems"
          }
        },
        {
          "valueCoding": {
            "id": "82ea21c8-15d7-483e-8283-e536b888da91",
            "code": "delivery_problems",
            "system": "urn:uuid:fca5e3c1-1f62-4d7c-97a4-f03303c1a659",
            "display": "Delivery Problems"
          }
        },
        {
          "valueCoding": {
            "id": "f1b7fbe8-4cbe-4361-c8dd-bc37452ecf44",
            "code": "pnc_problem",
            "system": "urn:uuid:fca5e3c1-1f62-4d7c-97a4-f03303c1a659",
            "display": "PNC Problems"
          }
        },
        {
          "valueCoding": {
            "id": "ce21d4d6-fa94-4ca9-8235-6b40d7bdd938",
            "code": "child_problems",
            "system": "urn:uuid:fca5e3c1-1f62-4d7c-97a4-f03303c1a659",
            "display": "Child Problems"
          }
        },
        {
          "valueCoding": {
            "id": "2052cb16-bb05-4402-8bab-836316de529b",
            "code": "adolescent_problems",
            "system": "urn:uuid:fca5e3c1-1f62-4d7c-97a4-f03303c1a659",
            "display": "Adolescent Problems"
          }
        },
        {
          "valueCoding": {
            "id": "22dad9d8-6573-4e6d-ce52-31f44d78f1b9",
            "code": "problems_eyes",
            "system": "urn:uuid:fca5e3c1-1f62-4d7c-97a4-f03303c1a659",
            "display": "Eye Problems"
          }
        },
        {
          "valueCoding": {
            "id": "7c1a5f41-52b5-42c2-af33-930e7660ffcf",
            "code": "diabetes",
            "system": "urn:uuid:fca5e3c1-1f62-4d7c-97a4-f03303c1a659",
            "display": "Diabetes"
          }
        },
        {
          "valueCoding": {
            "id": "44c78729-a0d2-4eca-8a79-e3bdf190d30c",
            "code": "high_blood_pressure",
            "system": "urn:uuid:fca5e3c1-1f62-4d7c-97a4-f03303c1a659",
            "display": "High Blood Pressure"
          }
        },
        {
          "valueCoding": {
            "id": "66d5589c-fac0-4af6-85a9-3d1c0aed7708",
            "code": "problems_with_birth_control",
            "system": "urn:uuid:fca5e3c1-1f62-4d7c-97a4-f03303c1a659",
            "display": "Birth Control Problems"
          }
        },
        {
          "valueCoding": {
            "id": "ca32b68f-e942-45e6-87d4-9db8c50f53cd",
            "code": "cataract_problem",
            "system": "urn:uuid:fca5e3c1-1f62-4d7c-97a4-f03303c1a659",
            "display": "Cataract Problems"
          }
        },
        {
          "valueCoding": {
            "id": "98e6fa08-ab4e-4348-8e7a-f5c6f05721b2",
            "code": "other",
            "system": "urn:uuid:fca5e3c1-1f62-4d7c-97a4-f03303c1a659",
            "display": "Others"
          }
        },
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-optionExclusive",
              "valueBoolean": true
            }
          ],
          "valueCoding": {
            "id": "7aa8e7b4-20e2-401a-913c-973ecd7e1ebc",
            "code": "no_problem",
            "system": "urn:uuid:fca5e3c1-1f62-4d7c-97a4-f03303c1a659",
            "display": "No Problem"
          }
        }
      ],
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl",
          "valueCodeableConcept": {
            "coding": [
              {
                "system": "http://hl7.org/fhir/ValueSet/questionnaire-item-control",
                "code": "check-box"
              }
            ]
          }
        }
      ]
    }
  ]
}
```

**Expected behavior**
Above questionnaire should work and deselect other options when selecting the option with `optionExclusive` extension and vice versa.

**Screenshots**
Screen_recording_20240211_113543

**Would you like to work on the issue?**
A PR is created which resolves the issue.

### PR DESCRIPTION
**Pull request by asad-zaman**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #2436

**Description**
Add `optionExclusive` extension support for `answerOption` in Popup for more than 10 items.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature)

**Screenshots (if applicable)**
answer-option-exclusive-in-popup

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Review by MJ1998 — APPROVED** [review]
Thanks for the changes @asad-zaman 

I think the solution is correct. I am just wondering if the number of options too huge then submitSelectedChange function should be optimized by tracking the items that are currently selected.

In the meantime, can you also add a testcase to verify the changes ?

**Review by MJ1998 — CHANGES_REQUESTED** [review]
Requested changes above!

**Comment by asad-zaman** [comment]
Hi @MJ1998,
I have added the test cases to verify the changes. Thanks

**Review by joiskash — CHANGES_REQUESTED** [review]
Can you please UTs to handle the two conditions described below:
1. What happens if there are more than one option exclusive answer options eg: "No Problem", "Not Valid"
2. What happens if there are "Other" rows already added and you click on option exclusive answer? eg: Open choice question with other options added.

**Comment by asad-zaman** [comment]
> Can you please UTs to handle the two conditions described below:
> 
> 1. What happens if there are more than one option exclusive answer options eg: "No Problem", "Not Valid"
> 2. What happens if there are "Other" rows already added and you click on option exclusive answer? eg: Open choice question with other options added.

Hi @joiskash,
I have added the mentioned test cases. Please check. Thanks

**Review by joiskash — COMMENTED** [review]
LGTM! cc: @jingtang10

**Review by jingtang10 — APPROVED** [review]

**Comment by asad-zaman** [comment]
Hi @jingtang10,
Could you please check now?

**Comment by asad-zaman** [comment]
HI @jingtang10,
Do I need to do anything from my side?

**Comment by asad-zaman** [comment]
Hi @jingtang10,
Could you please merge this PR? It passes all the requirements. Thanks

**Pull request merged**
