### PR TITLE
Custom widget to start application activity for result.

### LINKED ISSUE #1287: Custom widget that opens a new activity to collect answer
**Is your feature request related to a problem? Please describe.**
Create a custom widget that sends an intent to open a new activity (we can probably just pick a URL ourselves). In the new activity the developer should be able to use the activity result API to return the picked answer.

**Describe the solution you'd like**
A custom widget in the contrib folder of the sdc library

**Describe alternatives you've considered**
@soura-b fyi

**Additional context**
Na

**Would you like to work on the issue?**
Na

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1287 

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [ ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Comment by santosh-pingle** [comment]
@jingtang10 @aditya-07 draft

**Comment by santosh-pingle** [comment]
@jingtang10 @aditya-07 can you please review once?

**Comment by jingtang10** [comment]
@joiskash @santosh-pingle can you two figure out what the difference is between this and the example Kashyap provided? Why does that example need no library change?

If we figure that out I'm happy for us just to close this PR.

Thanks!

**Comment by santosh-pingle** [comment]
> 

Can you please share pr link for provided example @joiskash @jingtang10

**Comment by joiskash** [comment]
> > 
> 
> Can you please share pr link for provided example @joiskash @jingtang10

Sorry @santosh-pingle there is no PR for this. The repo is currently closed source, we are working to making it public. Until then you will have to refer to the sample we sent you via email. I will resend that email so that you can find it.

**Comment by santosh-pingle** [comment]
> > > 
> > 
> > 
> > Can you please share pr link for provided example @joiskash @jingtang10
> 
> Sorry @santosh-pingle there is no PR for this. The repo is currently closed source, we are working to making it public. Until then you will have to refer to the sample we sent you via email. I will resend that email so that you can find it.

@joiskash @jingtang10 I referred to the provided example OCLViewHolderFactory attachment, the only difference I see is that in the provided example custom widget is defined at application side, but rest of the implementation are almost the same.

OCLViewHolderFactory has a reference to a custom questionnaire fragment to launch the activity and to listen to the data through activity result api. It also observes results on livedata through fragment reference. These are the same changes.

In OCLViewHolderFactory, custom widget view is used to access the fragment reference, therefore no changes are required at sdc library to pass fragment reference to custom widget. (Where in current pr fragment reference is explicitly passed to QuestionnaireItemViewHolder as argument which can be avoided).

So, it is okay to close current pr.

**Pull request closed without merging**
