### PR TITLE
Edit Text Widget, Date Widget, Date + Time Widget All have been orien…

### PR DESCRIPTION
**Pull request by MuhammadSalman-7214**
…ted according to our latest text Question Orientation

### CODE REVIEW

**Review by jingtang10 — CHANGES_REQUESTED** [review]
Hi @MuhammadSalman-7214 thanks for this PR!

Looks good to me -- one thing, will you be able to figure out how to set the order of imports in android studio (i think you want alphabetically ordered rather than having java blocks at the end) and document your finding in https://github.com/google/android-fhir/wiki/Developer's-Guide in the set up section?

There're a few changes in this PR that change the order of imports which I think will actually break our spotless check.

**Comment by jingtang10** [comment]
please update once you're done.

**Comment by MuhammadSalman-7214** [comment]
> Hi @MuhammadSalman-7214 thanks for this PR!
> 
> Looks good to me -- one thing, will you be able to figure out how to set the order of imports in android studio (i think you want alphabetically ordered rather than having java blocks at the end) and document your finding in https://github.com/google/android-fhir/wiki/Developer's-Guide in the set up section?
> 
> There're a few changes in this PR that change the order of imports which I think will actually break our spotless check.

As we cannot configure IDE to follow spotlessApply rules, though we can set indentation and single import name, and I have updated that in developer documentation as well

**Review by jingtang10 — APPROVED** [review]
Thanks @MuhammadSalman-7214! Approved.

🎉

ps please resolve any conflicts before merging

**Pull request merged**
