### PR TITLE
Add code coverage tool to GitHub action script

### PR DESCRIPTION
**Pull request by deepankarb**

### CODE REVIEW

**Comment by jingtang10** [comment]
Hey @deepankarb sorry haven't looked at this - is this still a draft or ready for review? Thanks :)

**Comment by deepankarb** [comment]
> Hey @deepankarb sorry haven't looked at this - is this still a draft or ready for review? Thanks :)

Still draft :) Jacoco integrated. Codecov integration WIP.

**Comment by jtournier23** [comment]
@deepankarb is this the correct issue tracking the code coverage work you're doing? If so can you please update it with the latest status? Thanks

**Comment by deepankarb** [comment]
Closing this draft, no longer relevant. See #502 for code coverage implementation.

**Pull request closed without merging**
