### PR TITLE
create a maven repo from builds

### PR DESCRIPTION
**Pull request by yigit**
This PR adds a workflow to create a maven repo from builds

This simply attaches the build id to the version. We may eventually
make it duplicate the publication and also release with the right
version which we can use to upload to gmaven.

### CODE REVIEW

**Comment by yigit** [comment]
triggering presubmit to see if it works :)

**Comment by jingtang10** [comment]
@yigit how can this be tested? I struggled to find documentation online on the workflow.

**Review by jingtang10 — CHANGES_REQUESTED** [review]
can you document (however briefly) how this can be used in either the readme file or in the user's guide on the wiki page? thanks!

https://github.com/google/android-fhir/wiki//User's-Guide

**Review by jingtang10 — APPROVED** [review]
Thanks for updating the wiki.

**Pull request merged**
