### PR TITLE
Bump Jackson versions in (only) buildscript from 2.15.2 to 2.15.3

### PR DESCRIPTION
**Pull request by vorburger**
This is better than #2283 and #2285.

### CODE REVIEW

**Comment by vorburger** [comment]
Please hold with reviewing and merging this; I'll try to do this differently (via #2302)...

**Comment by vorburger** [comment]
Re-un-drafting this, following #2305, please do now review and merge this PR, as-is.

**Comment by vorburger** [comment]
@aditya-07 re. @jingtang10 feedback on Chat that you may be working on something related, just to synchronize:

Can you point me to bug / PR that you are working on related to Jackson? This PR only does a minor version bump of the `buildscript` dependencies, if you are working on the **_runtime_** Jackson dependency versions (in https://github.com/google/android-fhir/blob/master/buildSrc/src/main/kotlin/Dependencies.kt), then this is unrelated and OK to merge as-is - LGTY?

**Comment by vorburger** [comment]
@aditya-07 on Chat pointed out that [the runtime (APK) dependencies class](https://github.com/google/android-fhir/blob/master/buildSrc/src/main/kotlin/Dependencies.kt) has comments related to  jackson support on Android 24, which is our minimum supported version, so maybe bumping up Jackson version could end up breaking stuff.

However this PR only bumps the `buildscript` Jackson dependency versions, in [`settings.gradle.kts`](
https://github.com/google/android-fhir/blob/master/settings.gradle.kts) - which is a completely separate classpath scope.

To the best of my knowledge, given that this PR fully passes the build, this is safe to merge.

Please review?

**Review by aditya-07 — APPROVED** [review]
LGTM

**Review by omarismail94 — APPROVED** [review]

**Pull request merged**
