### PR TITLE
Date time picker component workflow.

### LINKED ISSUE #1085: Catalog, date time picker component workflow.
**Is your feature request related to a problem? Please describe.**

1. User click on date time picker component.
2. It launches date time picker screen with questionnaire, which demonstrate date time picker uses.
3. Click on navigation back key in action bar, it takes user back on landing page.

Design date time picker questionnaire json.
Write api to fetch date time picker questionnaire json file name.
Apply custom style at application side.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Design date time picker questionnaire json.
Write api to fetch date time picker questionnaire json file name.
Apply custom style at application side.

Fixes #1085 

**Description**
Clear and concise code change description. 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Feature 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Comment by Tarun-Bhardwaj** [comment]
@santosh-pingle , is the bug #1083 linked to the changes you are making as part of this PR?
CC: @ktarasenko has created PR #1089 to fix this bug

**Review by jingtang10 — APPROVED** [review]

**Review by jingtang10 — CHANGES_REQUESTED** [review]
hang on - this is date time picker rather than date picker right?

**Comment by santosh-pingle** [comment]
> hang on - this is date time picker rather than date picker right?

We have separated PR for date picker #1046
This PR was originally for time picker, but as of now sdc does not have time picker implementation, but it has for date time picker.
Therefore, this pr dateTime picker.
Time picker text is changed to Date time picker text.

**Comment by jingtang10** [comment]
@shelaghm the question might need to be updated because this is date time not time.

Santosh can you work with Shelagh and get a new string in before merge? Thanks

**Review by jingtang10 — APPROVED** [review]

**Comment by shelaghm** [comment]
Screen Shot 2022-02-09 at 22 13 57

I've updated the copy. @santosh-pingle I'll send a message with link to Figma file

**Pull request merged**
