### PR TITLE
The checkbox is very close to the left edge

### LINKED ISSUE #1477: The checkbox is very close to the left edge
**Describe the bug**
The checkbox is very close to the left edge.

unnamed

**Component**
Core library, SDC library, reference app, or SDC gallery app

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1477 

**Description**
Icons get drawn with start bound zero. If padding attribute is set with some value then it only get applied to the text.
Updated radio/checkbox icons which includes start bound / left padding.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix 

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Comment by santosh-pingle** [comment]
@shelaghm 

Attaching screenshots.   

Before Change
Screen Shot 2022-09-07 at 12 58 25 PM
Screen Shot 2022-09-07 at 12 58 02 PM


After change
Screen Shot 2022-09-27 at 6 30 49 PM
Screen Shot 2022-09-27 at 6 30 41 PM
Screen Shot 2022-09-27 at 6 30 27 PM
Screen Shot 2022-09-27 at 6 30 00 PM
Screen Shot 2022-09-27 at 6 29 38 PM

**Review by jingtang10 — COMMENTED** [review]
actually i have an issue with this approach. you're basically using a wider icon with the actual checkbox/radio button slight to the right? what happens in a right-to-left RTL setting (e.g. Arabic)?

**Comment by shelaghm** [comment]
@santosh-pingle Yay, finally looks the way we expect. Have you discussed another approach with @jingtang10 on how to achieve this without adding padding directly to the icons?

**Comment by santosh-pingle** [comment]
Let me check RTL setting whether we need another set of icons with right padding, or icons with left and right padding.

**Comment by santosh-pingle** [comment]
> actually i have an issue with this approach. you're basically using a wider icon with the actual checkbox/radio button slight to the right? what happens in a right-to-left RTL setting (e.g. Arabic)?

looking into it.

**Comment by santosh-pingle** [comment]
@shelaghm 
Can you please share `layout direction RTL` variant for these icons, means instead of left padding just add right padding to the icons (mirroring of these icons).


Android supports ltr and rtl qualifiers on res folder, so basically it only requires to add rtl variant drawables to the rtl resource folder nothing else.

**Comment by jingtang10** [comment]
have you tried this @santosh-pingle ?

**Comment by jingtang10** [comment]
actualy i'm not sure sure that'll work - so maybe try this: https://stackoverflow.com/questions/28301636/android-set-padding-to-radiobutton-pin

so you can use the same drawable but different insets for ltr and rtl.

**Comment by santosh-pingle** [comment]
> actualy i'm not sure that'll work - so maybe try this: https://stackoverflow.com/questions/28301636/android-set-padding-to-radiobutton-pin
> 
> so you can use the same drawable but different insets for ltr and rtl.

I am looking into it, thanks!

**Comment by santosh-pingle** [comment]
@jingtang10 @shelaghm 

Attaching screenshots for rtl layout direction.   
    
   

Screen Shot 2022-09-29 at 1 16 06 PM


Screen Shot 2022-09-29 at 1 15 51 PM

Screen Shot 2022-09-29 at 1 15 39 PM

Screen Shot 2022-09-29 at 1 15 23 PM



Screen Shot 2022-09-29 at 1 15 12 PM

**Review by jingtang10 — APPROVED** [review]
thanks santosh!

**Pull request merged**
