### PR TITLE
Update modal dialog colorPrimary value.

### LINKED ISSUE #1402: Modal widget in catalog app show blue color background.
**Describe the bug**

Below changes are seen after updating questionnaire theme as material3 theme.

- Modal widget in catalog app has blue color background.
- Also  on user click answer option does not show selected background.

**Component**
SDC library, reference app,

**To Reproduce**

**Expected behavior**
Show blue container background color.

**Screenshots**

Screen Shot 2022-05-19 at 3 09 04 PM

Screen Shot 2022-05-19 at 3 09 25 PM

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

### PR DESCRIPTION
**Pull request by santosh-pingle**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1402 

**Description**
Clear and concise code change description. 
Updated color primary value with color surface value for modal dialog style.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: Bug fix 

**Screenshots (if applicable)**
Before : 
Screen Shot 2022-05-19 at 3 09 25 PM

After :
Screen Shot 2022-05-19 at 7 49 05 PM

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md).
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [x] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Review by jingtang10 — COMMENTED** [review]
If we build a new app with default material3 themes, will the dialog have a blue background?

Or does the fix really lie in the library? I'm not so convinced. Are we doing something wrong in the catalog app?

**Review by jingtang10 — COMMENTED** [review]
If we build a new app with default material3 themes, will the dialog have a blue background?

Or does the fix really lie in the library? I'm not so convinced. Are we doing something wrong in the catalog app?

**Comment by santosh-pingle** [comment]
> @juanchazo fyi - if you can help with debugging this it would be great thanks!

This PR is no more valid PR.
This change is not required anymore.
This change was quick/temporary fix, before applying color theme as per material 3.
Therefore, I am closing this Pr.

> If we build a new app with default material3 themes, will the dialog have a blue background?
> 
> Or does the fix really lie in the library? I'm not so convinced. Are we doing something wrong in the catalog app?

This PR is no more valid PR.
This change is not required anymore.
This change was quick/temporary fix, before applying color theme as per material 3.
Therefore, I am closing this Pr.

**Comment by santosh-pingle** [comment]
> If we build a new app with default material3 themes, will the dialog have a blue background?
> 
> Or does the fix really lie in the library? I'm not so convinced. Are we doing something wrong in the catalog app?


This PR is no more valid PR.
This change is not required anymore.
This change was quick/temporary fix, before applying color theme as per material 3.
Therefore, I am closing this Pr.

**Comment by santosh-pingle** [comment]
https://github.com/google/android-fhir/pull/1431

**Pull request closed without merging**
