### PR TITLE
Update flag with decimal point

### LINKED ISSUE #1181: Data Capture - soft keyboard of widget type 'decimal' does not have a decimal point
**Describe the bug**
In a questionnaire, when a field set to type 'decimal' receives focus, the soft keyboard appears but it has not decimal point to select from.

**Component**
SDC gallery app

**To Reproduce**
1. Create a questionnaire with a field with the type set to 'decimal'
2. Open the questionnaire in the app
3. Set focus on the field
4. The numeric soft keyboard will appear but without the decimal point

**Expected behavior**
A numeric keyboard should appear with a decimal point option.

**Screenshots**
This is what the soft keyboard looks like on a field set to type 'decimal':
Screenshot_20220218-164945_mwcore

This is what the soft keyboard should look like (screenshot taken from the Radio android app):
Screenshot_20220218-164458_Radio

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
In the Data Capture Gallery app, you can view this in the "Neonate record from New South Wales, Australia" questionnaire. The birth weight field is a decimal but exhibits the same problem.

**Would you like to work on the issue?**
I don't know who can look into this but I would appreciate if someone looked into this as soon as possible.

### PR DESCRIPTION
**Pull request by epicadk**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1181 

**Description**
Clear and concise code change description. 

If the questionnaire is expecting a decimal answer then we should probably have the keyboard with decimal points.

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

-

**Type**
Choose one: Bug fix

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Comment by epicadk** [comment]
@jingtang10 uploads have been failing quite often lately.

**Comment by jingtang10** [comment]
@epicadk can you please complete the PR description section?

@vvikramraj can you please leave a review? thanks!

**Review by vvikramraj — COMMENTED** [review]
It appears that adding a test to verify that the desired soft keyboard is displayed is harder than I thought. Can you please add a screenshot so we can verify that the desired change is seen?

**Comment by epicadk** [comment]
> It appears that adding a test to verify that the desired soft keyboard is displayed is harder than I thought. Can you please add a screenshot so we can verify that the desired change is seen?

I can try, but this would depend on the keyboard the end user is using.

**Comment by vvikramraj** [comment]
> 

I would recommend attaching a screenshot to the description first so we can get this change in. We could then independently explore testing to verify that the desired keyboard is shown.

**Review by jingtang10 — APPROVED** [review]

**Comment by jingtang10** [comment]
agreeing with @vvikramraj... indeed, this is something really hard to test. i would say this is probably something best covered by screenshot testing.

**Comment by epicadk** [comment]
@jingtang10 can you rerun the failed workflow runs?

**Pull request merged**
