### PR TITLE
Add immunization measles workflow test

### PR DESCRIPTION
**Pull request by delcroip**
**Description**

add test for measles plandefinition
fix the testing repository implementation by making search nullable (call with null in valueset expand https://github.com/cqframework/clinical-reasoning/issues/365) 

**Alternative(s) considered**
Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Builds | Releases | Other)

**Screenshots (if applicable)**

**Checklist**
- [x ] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md).
- [ ] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page.
- [ ] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate ).
- [ ] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach.
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project.
- [ ] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally.
- [ ] I have built and run the demo app(s) to verify my change fixes the issue and/or does not break the demo app(s).

### CODE REVIEW

**Comment by jingtang10** [comment]
can you please give the pr a descriptive name @delcroip? thanks!

**Comment by jingtang10** [comment]
I think this needs `gradle spotlessApply` to format the code.

**Review by jingtang10 — COMMENTED** [review]
thanks @delcroip! so this also download the entire ig to the resource folder? in https://github.com/google/android-fhir/pull/2261 the ig is saved in `sampledata/smart-imm` and here they are saved in `resources`. do you think it's easy to unify?

**Comment by delcroip** [comment]
Please close this one

**Comment by jingtang10** [comment]
thanks @delcroip!

**Pull request closed without merging**
