### PR TITLE
Use macos-latest instead of macos-11 in GitHub Actions 

### LINKED ISSUE #1120: EncryptedDatabaseErrorTest Failing
Tracking bug for the currently failing CI.

e.g.
https://github.com/google/android-fhir/runs/5077468637?check_suite_focus=true

```
com.google.android.fhir.db.impl.EncryptedDatabaseErrorTest > unencryptedDatabase_thenEncryptedDatabase_shouldThrowIllegalStateException[test(AVD) - 10] FAILED 
	java.lang.AssertionError: unexpected exception type thrown; expected:<java.lang.IllegalStateException> but was:<java.lang.OutOfMemoryError>
	at org.junit.Assert.assertThrows(Assert.java:1020)

com.google.android.fhir.db.impl.EncryptedDatabaseErrorTest > encryptedDatabase_thenUnencrypted_shouldThrowIllegalStateException[test(AVD) - 10] FAILED 
	java.lang.AssertionError: unexpected exception type thrown; expected:<java.lang.IllegalStateException> but was:<java.lang.OutOfMemoryError>
	at org.junit.Assert.assertThrows(Assert.java:1020)

com.google.android.fhir.db.impl.EncryptedDatabaseErrorTest > encryptedDatabase_thenLostKey_shouldThrowSQLiteException[test(AVD) - 10] FAILED 
	java.lang.AssertionError: unexpected exception type thrown; expected:<net.sqlcipher.database.SQLiteException> but was:<java.lang.OutOfMemoryError>
	at org.junit.Assert.assertThrows(Assert.java:1020)

com.google.android.fhir.db.impl.EncryptedDatabaseErrorTest > encryptedDatabase_thenLostKey_recreationStrategy_shouldRecreateDatabase[test(AVD) - 10] FAILED 
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
```

We use emulator to run these test and in the past we ran into issues when there's a new emulator release: https://github.com/ReactiveCircus/android-emulator-runner/issues/160

### PR DESCRIPTION
**Pull request by jingtang10**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #1120 

**Description**
Use macos-latest instead of macos-11 in GitHub Actions. This reverses the change in #576.

cc @epicadk 

**Alternative(s) considered**
NA

**Type**
Choose one: Testing

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read the [Contributing](https://github.com/google/android-fhir/wiki/Contributing) page
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Comment by jingtang10** [comment]
cc @epicadk

**Comment by jingtang10** [comment]
open

**Review by stevenckngaa — APPROVED** [review]

**Review by epicadk — APPROVED** [review]
Looks good to me. Although not sure if we still want this because the tests are passing now. Disabling auto merge for that reason.

**Comment by jingtang10** [comment]
Not just for the ci issue but i think using the latest image is probably the best practice.

The original fix was meant to be temporary anyway. For that reason I'm gonna merge this.

**Pull request merged**
