### PR TITLE
Introduce Version Catalog, initially intentionally only for Glide

### PR DESCRIPTION
**Pull request by vorburger**
see #2302 

My expectation is that if this passes CI and gets merged, Dependabot will automagically propose a bump for Glide - let's try and see.

If this works, we should then migrate to this model. Perhaps that's something that could be "crowd sourced" and fanned out, instead of me doing all migrations myself?

PS: There would be an intermediate phase with "mixed" dependency declaration; to me such a "gradual adoption" is a "feature not a bug", with testing each change, and more sensible than a single big bang all in one migration.

### CODE REVIEW

**Comment by omarismail94** [comment]
This is actually VERY nice!! I never knew about this:
https://docs.gradle.org/current/userguide/platforms.html

Superb job!

**Review by omarismail94 — APPROVED** [review]

**Comment by vorburger** [comment]
> Superb job!

🙇🏽  but credit where credit is due - I learnt about this after doing research [starting from this comment](https://github.com/google/android-fhir/issues/2195#issuecomment-1743606990)!

> https://docs.gradle.org/current/userguide/platforms.html

see #2302, also https://developer.android.com/build/migrate-to-catalogs, and https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#gradle for why _"My expectation is that if this passes CI and gets merged, Dependabot will automagically propose a bump for Glide - let's try and see."_

**Comment by jingtang10** [comment]
this is lovely. thanks @vorburger!

**Comment by jingtang10** [comment]
`If this works, we should then migrate to this model. Perhaps that's something that could be "crowd sourced" and fanned out, instead of me doing all migrations myself?` -> agreed.

**Pull request merged**
