### PR TITLE
Add custom style attributes

### LINKED ISSUE #501: Create examples of custom style in the sdc gallery application
**Is your feature request related to a problem? Please describe.**
We should create examples in the sdc gallery app to show how implementers can change the color/style/text appearance of the questionnaire to match their application.

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
This could be hard-coded for certain questionnaires, or maybe we can even have a control panel where the user can choose from a list of colors, text appearances to customize the questionnaire.

**Additional context**
NA

**Would you like to work on the issue?**
NA

### PR DESCRIPTION
**Pull request by FikriMilano**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #501 (GSOC Project)

**Description**
Create default style for the views in Data Capture Library then override it in SDC Gallery and change it with our own custom style.

**Alternative(s) considered**
N.A

**Type**
Choose one: Feature

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Comment by Tarun-Bhardwaj** [comment]
@FikriMilano , is this PR ready for review?

**Comment by FikriMilano** [comment]
@Tarun-Bhardwaj , yes this PR is ready for review

**Comment by FikriMilano** [comment]
Minor changes on the header, it should be ready for review now

**Comment by Tarun-Bhardwaj** [comment]
@FikriMilano , could you please assign this PR to your mentor for an initial review?

**Comment by FikriMilano** [comment]
> @FikriMilano , could you please assign this PR to your mentor for an initial review?

Sure.
@qiarie

**Comment by Tarun-Bhardwaj** [comment]
> > @FikriMilano , could you please assign this PR to your mentor for an initial review?
> 
> Sure.
> @qiarie

@qiarie , assigned the PR to you for an initial review. Adita/Jing/Steven/Kevin would review it once you are done before the changes are merged. CC: @jingtang10

**Comment by santosh-pingle** [comment]
Working/looking into it. Thanks!

**Comment by santosh-pingle** [comment]
LGTM

**Comment by qiarie** [comment]
@FikriMilano Please update master

**Comment by FikriMilano** [comment]
Could someone give me some insight on how to test this? because a huge part of the changes are from xml

**Review by jingtang10 — CHANGES_REQUESTED** [review]
1. I was testing this and couldn't get thing to work... and then realised that in `values-night/themes.xml` the theme override isn't set.... can you please add this to the that file similar to `value/themes.xml`:

```
        <!-- Customize theme for questionnaires in this application. -->
        <item name="questionnaire_theme">@style/Theme.MyQuestionnaire</item>
```

2. Please rename the PR name to something like `Add custom style attributes`
3. I think the most critical part of this PR is that you're adding the custom style attributes, I don't feel it's necessarily that useful to provide an example for each one in the datacapturegallary app - I think you can simplify that file, having one or two examples is enough, especially no need to override the tint effect for radio buttons.

**Comment by FikriMilano** [comment]
Alright, thanks for the feedback

**Review by jingtang10 — APPROVED** [review]

**Pull request merged**
