### PR TITLE
Enable coverage on debug builds and upload to codecov

### LINKED ISSUE #233: >95% unit test code coverage
* Jacoco
* Codecov?

### LINKED ISSUE #671: Enable code coverage in CI
For robust, well-tested code base we should target high code coverage. We should be able to track code coverage and changes per PR in CI.

* Gradle offers a Jacoco plugin and options to configure. 
* There are plugins and 3p sites like coveralls and codecov.io that offer deeper insights in to coverage over time.

### PR DESCRIPTION
**Pull request by deepankarb**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #671 

**Description**
* Generate coverage reports using built-in jacoco plugin
* Upload report to codecov.io

**Alternative(s) considered**
Coveralls is another coverage report provider but we need add a plugin to upload reports which might impact build times. However this a weak criteria and it should be re-considered.

**Type**
Choose one: Testing

**Screenshots (if applicable)**

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Comment by jingtang10** [comment]
is there a way for you to generate an example report and post here?

**Comment by jtournier23** [comment]
Quick notes, for path that are not covered by choice, can you please ensure to document it in this PR? Thanks

**Comment by deepankarb** [comment]
> Quick note, for path that are not covered by choice, can you please ensure to document it in this PR? Thanks

Currently covering only the `engine` module. Need to include the remaining modules with additional config and testing.

**Comment by deepankarb** [comment]
@jingtang10 This PR uses [gradle-android-junit-jacoco-plugin](https://github.com/vanniktech/gradle-android-junit-jacoco-plugin) which dynamically creates coverage tasks for android and kotlin projects taking into account build variants and types.

It also adds coverage tasks as [dependencies](https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/blob/master/src/main/groovy/com/vanniktech/android/junit/jacoco/GenerationPlugin.groovy#L270) on the `check` task. `build` depends upon `check` hence coverage is calculated on check. 

Since coverage includes instrumentation tests, the build fails if there's no connected device.

As a workaround, we're running build with an emulator. A concrete solution should not have this dependency. 
I tried replicating the approach from (opensrp-app)[https://github.com/opensrp/opensrp-client-core/blob/master/opensrp-app/build.gradle#L307] in kotlin gradle DSL but for some reason the classes are not being picked up.

**Review by jingtang10 — APPROVED** [review]
Great! Thanks Deepankar!

**Pull request merged**
