### PR TITLE
Updated LogTags

### LINKED ISSUE #406: Hardcoded Log tags
**Describe the Issue**
Log tags have been hardcoded, individually in all log-tag statements. Instead, we should use, log-Tag with class names in every files, for all the log tags present in that file. 
This can be done, by defining a log-tag , inside the class, So that it can be reused , in every log-statements of that file. 

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by Ana2k**
**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #406

**Description**
Added class name relevant logtags 

**Alternative(s) considered**
Its easier to use universal LogTag as class Name

**Type**
Choose one: Code health 

**Screenshots (if applicable)** 
N/A

**Checklist**
- [x] I have read and acknowledged the [Code of conduct](https://github.com/google/android-fhir/blob/master/docs/CODE_OF_CONDUCT.md)
- [x] I have read [How to Contribute](https://github.com/google/android-fhir/blob/master/docs/contributing.md)
- [x] I have read the [Developer's guide](https://github.com/google/android-fhir/wiki/Developer's-Guide)
- [x] I have signed the Google [Individual CLA](https://cla.developers.google.com/about/google-individual), or I am covered by my company's [Corporate CLA](https://cla.developers.google.com/about/google-corporate )
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the style guide of this project
- [x] I have run `./gradlew check` and `./gradlew connectedCheck` to test my changes locally
- [x] I have built and run the reference app(s) to verify my change fixes the issue and/or does not break the reference app(s)

### CODE REVIEW

**Comment by jingtang10** [comment]
have you considered using timber https://github.com/JakeWharton/timber?

alternatively, something like this may be useful: https://muthuraj57.medium.com/logging-in-kotlin-the-right-way-d7a357bb0343

or this https://coralogix.com/blog/best-practices-for-logging-in-kotlin/

@yigit or @kevinmost may have an option on this also.

**Comment by Tarun-Bhardwaj** [comment]
> have you considered using timber https://github.com/JakeWharton/timber?
> 
> alternatively, something like this may be useful: https://muthuraj57.medium.com/logging-in-kotlin-the-right-way-d7a357bb0343
> 
> or this https://coralogix.com/blog/best-practices-for-logging-in-kotlin/
> 
> @yigit or @kevinmost may have an option on this also.

@Ana2k , did you get a chance to visit the URLs shared by Jing ? Could you please advise the next steps in before this PR can get merged?

**Comment by kevinmost** [comment]
I think Timber would be a good choice here, I'm happy to review the CL if you want to use it.

**Comment by Tarun-Bhardwaj** [comment]
> I think Timber would be a good choice here, I'm happy to review the CL if you want to use it.

@Ana2k , is there any progress on this issue based on the comments from Jing & Kevin?

**Comment by jingtang10** [comment]
I created a new issue to address this problem using timber #771. Closing this PR for now.

**Pull request closed without merging**
